/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio28;

import comunes.ColaDeClientes;
import comunes.ColaDeEventos;
import comunes.Evento;
import comunes.Exponencial;
import comunes.Sistema;
import comunes.TipoEvento;
import comunes.Uniforme;
import comunes.Utils;
import comunes.VectorDeEstado;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciano
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    DefaultTableModel model;

    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_Simular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_filasAMostrar = new javax.swing.JTextField();
        txt_horaCorte = new javax.swing.JTextField();
        lbl_horaCorte = new javax.swing.JLabel();
        lbl_iteraciones = new javax.swing.JLabel();
        txt_filasASimular = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteracion", "Hora", "Evento", "RND llegada", "t", "h", "Cola", "RND compra", "Cant compra", "t/art", "t/total", "h", "RND caja1", "t", "h", "RND caja2", "t", "h", "RND caja3", "t", "h", "Acum Compradores"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Simular.setText("Simular");
        btn_Simular.setToolTipText("ejemplo christian");
        btn_Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimularActionPerformed(evt);
            }
        });

        jLabel1.setText("Filas a mostrar");

        txt_filasAMostrar.setText("200");
        txt_filasAMostrar.setToolTipText("Ingrese la cant. de dias a simular");
        txt_filasAMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txt_horaCorte.setText("5");

        lbl_horaCorte.setText("Hora corte");

        lbl_iteraciones.setText("Iteraciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(btn_Simular))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_iteraciones)
                                    .addComponent(lbl_horaCorte))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_filasAMostrar)
                            .addComponent(txt_horaCorte)
                            .addComponent(txt_filasASimular))))
                .addContainerGap(586, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Simular)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_filasAMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_horaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_horaCorte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_filasASimular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_iteraciones))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimularActionPerformed

        // PASO 1: Resetear VALORES
        // borrarTabla(model);
        // PASO 2: Crear OBJETOS
        model = (DefaultTableModel) jTable1.getModel();

        Utils utils = new Utils();
        int rnd = utils.getRnd();
        Uniforme uniforme = new Uniforme(1, 10);
        Exponencial exp = new Exponencial(12);

        ColaDeEventos colaEventos = new ColaDeEventos();
        ColaDeClientes colaClientes = new ColaDeClientes();

        int contCompradores = 0;

        // PASO 3: Obtener parametros de la GUI
        int filasAmostrar = Integer.parseInt(txt_filasAMostrar.getText());
        int filasASimular = Integer.parseInt(txt_filasASimular.getText());
        float horaCorte = Integer.parseInt(txt_horaCorte.getText());

        // PASO 4: Valores iniciales primera iteracion
        colaEventos.agregarEvento(new Evento(0.0f, "Inicio", TipoEvento.INICIO));
        colaEventos.agregarEvento(new Evento(exp.getExponencial()));

        // Iteraciones (FOR, WHILE, ETC)
        // PASO 5: Calcular nuevos valores del Vector De Estado
        VectorDeEstado vectorEstado = new VectorDeEstado(0, Sistema.getHoraActual(), "Inicio", rnd, 0.0f, 0.0f, contCompradores);

        // PASO 5: Actualizar vector/es e iterar
        while (horaCorte > Sistema.getHoraActual() && filasASimular > vectorEstado.getIteracion()) {

            
            for (int n = 0; n < filasAmostrar; n++) {
                model.addRow(vectorEstado.toObjectArray());
                vectorEstado.setIteracion(vectorEstado.getIteracion() + 1);
                Sistema.setHoraActual(Sistema.getHoraActual() + 1);
                vectorEstado.setHora(Sistema.getHoraActual());
            }
        }


    }//GEN-LAST:event_btn_SimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Simular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_horaCorte;
    private javax.swing.JLabel lbl_iteraciones;
    private javax.swing.JTextField txt_filasAMostrar;
    private javax.swing.JTextField txt_filasASimular;
    private javax.swing.JTextField txt_horaCorte;
    // End of variables declaration//GEN-END:variables

    public void borrarTabla(DefaultTableModel model) {
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }
}
