/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio146;


import comunes.Tablas;
import comunes.Utils;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciano
 */
public class Pantalla extends javax.swing.JFrame {
int filasASimular;
int filasAMostrar;
float precioLitro;
float precioVenta;
float precioDevolucion;
int litrosA;
int litrosB;
int litrosC;
int litrosD;
int iteracion;

    /**
     * Creates new form Pantalla
     */
    DefaultTableModel model;

    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_Simular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_IteracionesAMostrar = new javax.swing.JTextField();
        lbl_iteraciones = new javax.swing.JLabel();
        txt_Iteraciones = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_precioLitro = new javax.swing.JTextField();
        txt_precioVenta = new javax.swing.JTextField();
        txt_PrecioDevolucion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_litrosA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_litrosB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_litrosC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_litrosD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "LA", "LB", "LC", "LD", "rnd Dem A", "litros Dem A", "VA", "IA", "SA", "PA", "RAl", "rnd Dem B", "litros Dem B", "VB", "IB", "SB", "PB", "RB", "rnd Dem C", "litros Dem C", "VC", "IC", "SC", "PC", "RC", "rnd Dem D", "litros Dem D", "VD", "ID", "SD", "PD", "RD", "Resultado Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Simular.setText("Simular");
        btn_Simular.setToolTipText("ejemplo christian");
        btn_Simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimularActionPerformed(evt);
            }
        });

        jLabel1.setText("Iteraciones a mostrar");

        txt_IteracionesAMostrar.setText("200");
        txt_IteracionesAMostrar.setToolTipText("Ingrese la cant. de dias a simular");
        txt_IteracionesAMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_iteraciones.setText("Iteraciones");

        txt_Iteraciones.setText("100");

        jLabel2.setText("Precio litro");

        jLabel3.setText("Precio Venta");

        jLabel4.setText("Precio Devolucion");

        txt_precioLitro.setText("1,1");

        txt_precioVenta.setText("2");

        txt_PrecioDevolucion.setText("0,2");

        jLabel5.setText("Litros B");

        txt_litrosA.setText("22");

        jLabel6.setText("Litros C");

        txt_litrosB.setText("22");

        jLabel7.setText("Litros A");

        txt_litrosC.setText("22");

        jLabel8.setText("Litros D");

        txt_litrosD.setText("24");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Simular)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_IteracionesAMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_iteraciones)
                                                .addGap(70, 70, 70)
                                                .addComponent(txt_Iteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_PrecioDevolucion)
                                    .addComponent(txt_precioVenta)
                                    .addComponent(txt_precioLitro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_litrosD)
                    .addComponent(txt_litrosC)
                    .addComponent(txt_litrosB)
                    .addComponent(txt_litrosA, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_Simular)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_precioLitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_precioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_iteraciones)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txt_IteracionesAMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txt_Iteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_PrecioDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_litrosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_litrosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_litrosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_litrosD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1262, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimularActionPerformed

        // PASO 1: Resetear VALORES        
        borrarTabla(model);
        
        // PASO 2: Crear OBJETOS
        model = (DefaultTableModel) jTable1.getModel();
        Utils utils = new Utils();

        // PASO 3: Obtener parametros de la GUI
        
        int iteracionesASimular = Integer.parseInt(txt_Iteraciones.getText());
        int iteracionesAMostrar = Integer.parseInt(txt_IteracionesAMostrar.getText());
        
        float precioLitro = Integer.parseInt(txt_precioLitro.getText());
        float precioVenta = Integer.parseInt(txt_precioVenta.getText());
        float precioDevolucion = Integer.parseInt(txt_PrecioDevolucion.getText());
        
        int litrosA = Integer.parseInt(txt_litrosA.getText());
        int litrosB = Integer.parseInt(txt_litrosB.getText());
        int litrosC = Integer.parseInt(txt_litrosC.getText());
        int litrosD = Integer.parseInt(txt_litrosD.getText());
        

        // PASO 4: Valores iniciales primera iteracion
        iteracion = 0;
        
        // Iteraciones (FOR, WHILE, ETC) ------------------------------------------------------------------------------------------------------------------------
        
        // PASO 5: Calcular nuevos valores
        
        int rndA = utils.getRnd();
        int rndB = utils.getRnd();
        int rndC = utils.getRnd();
        int rndD = utils.getRnd();
        
        int demA = Tablas.getValorIntervalo(rndA, Tablas.getTablaDemandaA());
        int demB = Tablas.getValorIntervalo(rndB, Tablas.getTablaDemandaB());
        int demC = Tablas.getValorIntervalo(rndC, Tablas.getTablaDemandaC());
        int demD = Tablas.getValorIntervalo(rndD, Tablas.getTablaDemandaD());
        
        // PASO 6: 
        while (iteracionesASimular > iteracion) {

            for (int n = 0; n < iteracionesAMostrar; n++) {
                //model.addRow("");
            }
            /*TODO: SOBRECARGA: SI ME SOLICITAN SIMULAR 1 MILLON DE ITERACIONES O
            1 MILLON DE HORAS
                - Las "filas" o "iteraciones" a mostrar deben estar limitadas por parametro
                    - Solicitar un parametro por UI que de superar las 1000 filas, deja de mostrar filas
                    - Con esto se limita la cantidad de veces que se llama al metodo "model.addRow" (ya que solo se llama hasta que se alcanzan
                      las 1000 filas o se alcanza el valor seteado por el usuario en la UI
                - Los calculos pueden seguir infinitamente, independientemente de que siga agregando fillas con "model.addRow" ya que en cada iteracion
                    piso el valor previo de la variable
            
            */
        }

    }//GEN-LAST:event_btn_SimularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Simular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_iteraciones;
    private javax.swing.JTextField txt_Iteraciones;
    private javax.swing.JTextField txt_IteracionesAMostrar;
    private javax.swing.JTextField txt_PrecioDevolucion;
    private javax.swing.JTextField txt_litrosA;
    private javax.swing.JTextField txt_litrosB;
    private javax.swing.JTextField txt_litrosC;
    private javax.swing.JTextField txt_litrosD;
    private javax.swing.JTextField txt_precioLitro;
    private javax.swing.JTextField txt_precioVenta;
    // End of variables declaration//GEN-END:variables

    public void borrarTabla(DefaultTableModel model) {
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }
    
}
